packages:
  - apps/*
  - services/*
  - packages/*

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@sentry/cli'
  - '@virtality/schema'
  - core-js
  - esbuild
  - prisma
  - prisma-zod-generator
  - protobufjs
  - sharp
  - unrs-resolver

overrides:
  '@sentry/node-core@>=10.11.0 <10.27.0': '>=10.27.0'
  '@sentry/node@>=10.11.0 <10.27.0': '>=10.27.0'
  better-auth@<1.4.2: '>=1.4.2'
  better-auth@<1.4.5: '>=1.4.5'
  esbuild@<=0.24.2: '>=0.25.0'
  fast-xml-parser@>=5.0.9 <=5.3.3: '>=5.3.4'
  hono@<4.11.4: '>=4.11.4'
  hono@<4.11.7: '>=4.11.7'
  lodash@>=4.0.0 <=4.17.22: '>=4.17.23'
