export const ACCOUNT_MISMATCH_NOTICE_PARAM = 'notice'
export const ACCOUNT_MISMATCH_NOTICE_VALUE = 'account-mismatch'
export const ACCOUNT_MISMATCH_REDIRECT = `/?${ACCOUNT_MISMATCH_NOTICE_PARAM}=${ACCOUNT_MISMATCH_NOTICE_VALUE}`
