-- Subscription columns required by Better Auth Stripe (billingInterval, cancelAt,
-- canceledAt, endedAt, stripeScheduleId) already exist on this database.
-- This migration records the Prisma schema alignment; no DDL to apply.
